@startuml "Change password"
|User|
start

:Request to change password;
-> Validate user identity;
if (valid) then (yes)
  :Generate new password;
  :Update password in database;
  -> Notify user of change;
  :Password change successful;
else (no)
  -> Invalid user identity;
  :Password change failed;
endif

stop
@enduml
