@startuml "Issue warranty"
start
:Receive requirement;
:Check warranty;
if (The product is in warranty period) then (yes)
:Issue warranty;
:Export invoice;
else (no)
:Reject warranty request;
end
endif
stop
@enduml