@startuml "Reset password"
|User|
start

:Request to reset password;
- Validate user identity;
if (valid) then (yes)
  - Send password reset link;
  :User receives reset link;
  - Clicks on reset link;
  - Enter new password;
  - Update password in database;
  - Password reset successful;
else (no)
  - Invalid user identity;
  - Password reset failed;
endif

stop
@enduml
