@startuml
class Staff {
name: Char
phone: Char
email: Char
address: Char
job_position: Char
role: Char
image: Binary
labor_contract_start_date: Date
labor_contract_end_date: Date
labor_contract_image: Binaary
user_id: ResUser
create_user: boolean
department: Department
department_role: Char
_compute_staff_role()
action_create_user()
onchange()
send_email_to_selected_employees()
}

class Timekeeping {
name: Char
checkin_dat: Date
checkout_date: Date
staff: Staff
_computer_name()
}

class Department {
name: Char
description: Char
manager: Staff
staffs: List<Staff>
total_employee: Integer 
_compute_total_staff()
}

class ReportRequest {
deadline: Date
state: Char
title: Char
description: Char
report: List<Report>
assignee: Staff
departmnt: Department
user_id: Char
accept()
reject()
}

class ReportFile {
name: Char
description: Char
file: Binary
reqport: Report
}

class Report {
title: Char
content: Char
state: Char
files: List<ReportFile>
request: Char (ReportRequest)
}

class InterviewResult {
appointment: InterviewAppointment
staff: Staff
score: Float
comment: Char
_check_integer_range()
}

class InterviewAppointment {
time: Date
staffs: List<Staff>
applicant: Applicant
location: Char
state: Char
unlink()
}

class Applicant {
name: Char
phone: Char
email: Char
address: Char
birth: Date
apply_position: Char
image: Binary
cv: Binary
portfolio: Binary
state: Char
interview: List<InterviewAppopintment>
approve_applicant()
reject_applicant()
}

class Contact {
email: Char
title: Char
content: Char
customer: Customer
response List<Message>
}

class Customer {
name: Char
phone: Char
email: Char
address: Char
potentialPoint: Integer
}

class Message {
customer: Customer
title: Char
content: Char
}

class ReplyContact {
contact: Contact
title: Char
content: Char
staff: Staff
reply_contact(customerServiceStaff: Staff)
}


Timekeeping -- Staff
Staff --o Department
Staff -- ReportRequest
ReportRequest -- Department
Report *-- ReportFile
Report -- ReportRequest
InterviewAppointment o-- Staff
InterviewResult --o Staff
InterviewResult --o InterviewAppointment
InterviewAppointment --o Applicant
Staff --o ReplyContact
ReplyContact --o Contact
Contact --o Customer
Contact *-- Message

@enduml
