@startuml "Reset password"
autonumber
actor "Staff" as Staff
boundary "Account Management System Interface" as AMSI
control "Email system" as ES
control "Account Controller" as Ctl

Staff --> AMSI ++: Send reset password request
AMSI --> Ctl ++: Create reset password link
Ctl --> ES: Send reset password link via email
ES --> Staff: Reset password link
Staff --> AMSI: Enter reset password interface via email link
AMSI --> Ctl: New password
Ctl --> AMSI --: Notify success 
AMSI --> Staff --: Notify success
@enduml